# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tgErBCs4gR8h4lbbsWwSGi7RTd56OXrB
"""

from sklearn.datasets import load_iris
import numpy as np
import matplotlib.pyplot as plt

# Load the Iris dataset
iris = load_iris()
# Accessing the features (data) using NumPy array
X = np.array(iris.data) # (Features (sepal length, sepal width, petal length, petal width) #Accessing the target labels (species)
Y = np.array(iris.target) # Target variable (species: 0 for setosa, 1 for versicolor, 2 for virginica)

print("mean",np.mean(X))
print("median",np.median(X))
print("standard deviation",np.std(X))
print("min",np.min(X))
print("max",np.max(X))

sepal_features=X[:,:2]
# print("Sepal length and sepal width", sepal_features)




plt.scatter(X[:, 0], X[:, 1], c=Y, cmap='turbo')
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.title("Sepal Length vs Sepal Width")
plt.colorbar(label='Species')
plt.show()

plt.hist(X[:, 0], bins=20, color='DarkSeaGreen', edgecolor='black')
plt.xlabel("Sepal Length")
plt.ylabel("Frequency")
plt.title("Distribution of Sepal Length")
plt.show()

plt.plot(X[:, 2], X[:, 3], color='Maroon', marker='o')
plt.xlabel("Petal Length")
plt.ylabel("Petal Width")
plt.title("Petal Length vs Petal Width")
plt.show()